name: Release feature
on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: 'The release version.'
      java-version:
        required: false
        type: string
        description: 'Java SDK versjon som skal brukes.'
        default: '21'
      mvn-projects:
        required: false
        type: string
        description: 'Comma-delimited list of specified reactor projects to build instead of all projects.'
        default: ''
      release-branch:
        required: false
        type: string
        description: 'Hvilken branch skal releases. Default master.'
        default: 'master'
      release-file:
        required: false
        type: string
        description: "Hvilket pomfil som skal brukes"
    secrets:
      build-token:
        required: true
        description: 'Tokenet som brukes for build. '
      release-token:
        required: true
        description: 'Tokenet som brukes for Ã¥ release til maven registry. '

jobs:
  build:
    name: Release
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release-branch }}
      - name: Setup java and maven for build
        uses: navikt/sif-gha-workflows/.github/actions/maven/setup-java-and-maven@main # ratchet:exclude
        with:
          github-token: ${{ inputs.build-token }}
          java-version: ${{ inputs.java-version }}
      - name: Set version and build
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ inputs.release-version }} ${{ inputs.release-file }}
          mvn -B -s settings.xml package  ${{ inputs.mvn-projects }} -DtrimStackTrace=false -Dfile.encoding=UTF-8
      - name: Setup java and maven for build
        uses: navikt/sif-gha-workflows/.github/actions/maven/setup-java-and-maven@main # ratchet:exclude
        with:
          github-token: ${{ inputs.release-token }}
          java-version: ${{ inputs.java-version }}
      - name: Build
        run: |
          mvn -B -s settings.xml -Dmaven.wagon.http.pool=false -DskipTests deploy ${{ inputs.mvn-projects }} ${{ inputs.release-file }} -DtrimStackTrace=false -Dfile.encoding=UTF-8

